name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: 1.0.8
  equatable: 2.0.5
  faker: ^2.2.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  go_router: ^14.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
